export const navigation = [
  {
    title: "Roadmap",
    path: "/Roadmap",
  },
  {
    title: "Team",
    path: "/Team",
  },
  {
    title: "About",
    path: "/About",
  },
  {
    title: "Wallet",
    path: "/Wallet",
  },
];

export const partners = [
  {
    img: "/images/webflow.png",
  },
  {
    img: "/images/relume.png",
  },
];

export const about = [
  {
    title: "Thousands of unique NFTs",
    desc: "Each character is entirely unique and is generated by combining attributes such as colour palettes, skin tones, facial traits, outfits and accessories. With nearly endless combinations, all characters are guaranteed to be one of a kind.",
    img: "/images/about1.png",
    isBig: false,
  },
  {
    title: "Secure the most rare",
    desc: "Even though no two Tinyfaces will ever be the same, some variations are rarer than others. Watch out for special accessories and raw materials - the rarer the attributes, the rarer your character will be.",
    img: "/images/about2.png",
    isBig: false,
  },
  {
    title: "Our environmental impact matters to us.",
    desc: "In order to enable our community to spend as little as possible in gas fees when minting, we opted for a contract made by Azuki called ERC721A, which allows minting multiple NFTs for essentially the same cost as minting a single one.",
    img: "/images/about3.png",
    isBig: true,
  },
];

export const characters = [
  {
    img: "/images/NFT1.png",
  },
  {
    img: "/images/NFT2.png",
  },
  {
    img: "/images/NFT3.png",
  },
  {
    img: "/images/NFT4.png",
  },
  {
    img: "/images/NFT5.png",
  },
  {
    img: "/images/NFT1.png",
  },
  {
    img: "/images/NFT2.png",
  },
  {
    img: "/images/NFT3.png",
  },
  {
    img: "/images/NFT4.png",
  },
  {
    img: "/images/NFT5.png",
  },
];

export const questions = [
  {
    id: 1,
    title: "What is an NFT?",
    ans: "A non-fungible token is a unique digital identifier that is recorded on a blockchain, and is used to certify ownership and authenticity. It cannot be copied, substituted, or subdivided. The ownership of an NFT is recorded in the blockchain and can be transferred by the owner, allowing NFTs to be sold and traded."
  },
  {
    id: 2,
    title: "What makes our NFT special?",
    ans: "Every NFT contains a digital signature which makes each one unique. NFTs are digital assets and could be photos, videos, audio files, or another digital format. NFT examples include artwork, comic books, sports collectibles, trading cards, games and more."
  },
  {
    id: 3,
    title: "Who is involved in NFT?",
    ans: "People interested in Crypto-trading and people who like to collect artwork often use NFTs. Other than that, it has some other uses too like: Digital Content - The most significant use of NFTs today is in digital content."
  },
  {
    id: 4,
    title: "When does minting begin?",
    ans: "History of Money Minting. Coins were first minted over 2,000 years ago in the ancient kingdom of Lydia (modern-day Turkey). The ancient coins were minted by hand through striking blank pieces of metal such as gold, silver, or copper using hammers."
  },
  {
    id: 5,
    title: "What does minting an NFT means?",
    ans: "What Does It Mean To “Mint” an NFT? Minting an NFT means creating a unique token on a blockchain. Only after minting an NFT is the digital collectible stored on the blockchain. It's important to know what is being stored during the minting process."
  },
]